### ISSUE TITLE
Pear error 

### ISSUE THREAD

**Issue by manea-eugen** [chef-cookbooks/php#100]
Had anyone experience this error with php 5.5.9 on ubuntu 14.04.1?

I think it has to do with the fact that php 5.4  introduced mods-available/ instead of conf.d
I temporary managed to fix this issue by setting this in my attributes
default['php']['ext_conf_dir']  = File.join(File.dirname(node['php']['conf_dir']), 'mods-available')

==> default: [2014-11-12T08:49:22+00:00] INFO: Installing php_pear[xdebug]
==> default: 
==> default: ================================================================================
==> default: Error executing action `create` on resource 'template[/etc/php5/conf.d/xdebug.ini]'
==> default: ================================================================================
==> default: 
==> default: Chef::Exceptions::EnclosingDirectoryDoesNotExist
==> default: ------------------------------------------------
==> default: Parent directory /etc/php5/conf.d does not exist.
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/php/providers/pear.rb
==> default: 
==> default: 227:   template "#{node['php']['ext_conf_dir']}/#{name}.ini" do
==> default: 228:     source 'extension.ini.erb'
==> default: 229:     cookbook 'php'
==> default: 230:     owner 'root'
==> default: 231:     group 'root'
==> default: 232:     mode '0644'
==> default: 233:     variables(:name => name, :extensions => extensions, :directives => directives)
==> default: 234:     action action
==> default: 235:   end
==> default: 236: end
==> default: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/php/providers/pear.rb:227:in `manage_pecl_ini'
==> default: 
==> default: template("/etc/php5/conf.d/xdebug.ini") do
==> default:   provider Chef::Provider::Template
==> default:   action [:create]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   guard_interpreter :default
==> default:   path "/etc/php5/conf.d/xdebug.ini"
==> default:   backup 5
==> default:   atomic_update true
==> default:   source "extension.ini.erb"
==> default:   cookbook "php"
==> default: 
==> default:   variables {:name=>"xdebug", :extensions=>{"/usr/lib/php5/20121212/xdebug.so"=>false}, :directives=>{}}
==> default:   cookbook_name :xdebug
==> default:   mode "0644"
==> default:   owner "root"
==> default:   group "root"
==> default: end
==> default: 
==> default:

**Comment by cheeseplus** [comment]
Closed as fixed (and dupe)
