### ISSUE TITLE
PEAR installed APC has debugging enabled

### ISSUE THREAD

**Issue by leedo** [chef-cookbooks/php#102]
I can't seem to track down how or why this is the case. When I run manually the `pear` command that should be getting run, it doesn't seem to have debugging enabled.

`echo -e '\r' | pear install -a apc`

However, when installed via chef-client, APC ends up with debugging enabled, which makes it not terribly useful.

**Comment by cheeseplus** [comment]
Closing this one due to age but please open a new issue with distro specifics and a current reproduction case.
