### ISSUE TITLE
Error when installing from source, mysql::client does not exist anymore

### ISSUE THREAD

**Issue by cevou** [chef-cookbooks/php#106]
If you install PHP from source the recipe tries to call the mysql::client recipe. In the latest version of the mysql cookbook this recipe does not exist anymore. You have to go back to an old version of the mysql cookbook to make this work again.

**Comment by NathanielMichael** [comment]
Looking at the changes that happened in the mysql cookbook with version 6, it looks like we can just make a small change to get this working again.

Replace 

https://github.com/opscode-cookbooks/php/blob/c6a314b5eef964378d40d0c8b660e522b4cc51ab/recipes/source.rb#L25
```ruby
include_recipe 'mysql::client' if configure_options =~ /mysql/
```

with something like this

```ruby
if configure_options =~ /mysql/
  mysql_client 'default' do
    action :create
  end
end
```

Essentially we just need to make sure the mysql libs are installed to build against, this is what I interpret to be the proper way to do that.

I'm not able to test right now so I won't put in a PR until tomorrow, until then, any feedback?

**Comment by DQNEO** [comment]
This patch works fine for me.
:+1:

**Comment by cheeseplus** [comment]
This was merged, closing.
