### ISSUE TITLE
Errno::EFAULT: Bad address

### ISSUE THREAD

**Issue by jrvlima** [chef-cookbooks/php#117]
I'm new with chef, I'm getting an error to upload php cookbook. Do you guys know what I'm doing wrong.

**Comment by Rockstar04** [comment]
Hey @jrvlima have you figured out your issue here? There isnt much to go on. If you still have a problem could you give us a little more info to try to help you out?

**Comment by tas50** [comment]
I'm not able to reproduce this in the latest releases. If you're still having this problem can you give me more details on the release of the cookbook, your chef-client, and a full dump of the failure.
