### ISSUE TITLE
Cannot upgrade because of unwanted mysql dependency

### ISSUE THREAD

**Issue by acoulton** [chef-cookbooks/php#154]
Hi,

I cannot upgrade past 1.5.0 because 1.6.0 onwards have a hard dependency on `mysql >= 6.0.0` which conflicts with a number of other cookbooks in my project that are pinned to the `5.x` series of the mysql cookbook.

There are significant breaking changes between the `5.x` and `6.x` series of the mysql cookbook and the maintainers strongly recommend migrating to a new physical database server instance as part of that. I'll probably do that in due course, but it doesn't seem like I should be forced to work through all of that now (and whatever changes are required to deal with updates in other cookbooks I'm using depending on mysql) just because the php::source recipe (which I'm not using) wants to install a mysql client.

I don't anyway think a mysql client is actually required for installing php from source - surely it would make more sense for this cookbook to drop the mysql requirement altogether and allow the end-user to install a mysql client themselves prior to installing php if they actually want one?

**Comment by Rockstar04** [comment]
My concern is that they arent maintaining the 5.x branch with bug releases, so moving to 6.x is the only way to get updates for existing issues.

I agree that the hard dependency on the MySQL cookbook is unfortunate, but as far as I know there isnt a way to reliable specify an optional cookbook.

**Comment by acoulton** [comment]
> My concern is that they arent maintaining the 5.x branch with bug releases, so moving to 6.x is the only way to get updates for existing issues.

I appreciate that, but IMHO that is none of the php cookbook's business. End users should be able to choose whether and when to do major breaking updates of essentially unrelated components on their own terms, without that locking them out of bugfixes on separate cookbooks that have very limited overlap. It's not like you're actually using any significant mysql functionality in this cookbook.

> I agree that the hard dependency on the MySQL cookbook is unfortunate, but as far as I know there isnt a way to reliable specify an optional cookbook.

I don't think there is either (a shortcoming in chef). Given that, and considering how little of the php cookbook's functionality is affected, I feel quite strongly you should drop the mysql dependency and the mysql_client resource invokation altogether.

People who want to build php from source with mysql support are quite capable of adding the mysql client dependency in their own project cookbook / role / etc. It feels like that follows conventions of other cookbooks much more than forcing everyone to have the cookbook, and have it in a specific version, just in case a few people need it.

If you're concerned users might not understand why their php build has failed, you could always replace the `mysql_client` resource invokation in php::source with a check for an installed mysql client and throw an exception with instructions on what to do.

**Comment by Rockstar04** [comment]
That would be a break in backwards compatability, and @someara is already working on a complete, ground up rewrite on the cookbook. So unless the other maintainers are OK with a break in SemVer, I am not sure this can happen.

If there are specific bug fixes you need from 1.6+ you could rebase them against the 1.5.0 branch, submit a PR and we could try to tag them as a 1.5.x maintence release.

**Comment by acoulton** [comment]
@Rockstar04 sorry for the slow reply.

The changes I want from 1.6+ include the removal of php.ini quotes that you released in the BC-breaking 1.7.0 (per #141) so I don't see how they can be backported to 1.5.x.

Personally, if it was my cookbook (and given the issues over 1.7.0) I would remove the mysql dependency now as a breaking 2.0 release, unless @someara's full rewrite is very close to shipping.

If the rewrite is following conventions for the other newer official cookbooks, I'd assume there's a good chance the mysql dependency will be dropped in that release anyway - I don't see the harm in an intermediate release that takes us along that path.

**Comment by Rockstar04** [comment]
The decision to bump the major number would really come down to @someara and @tas50 

I'm not sure how far along the refactor is, Someara has a solid start, but last I talk to him it had hit some snags on how to handle some aspects.

**Comment by krues8dr** [comment]
Is there any progress on this?  I just ran aground on this while trying to use MariaDB instead of MySQL.

**Comment by iennae** [comment]
What are folks thoughts of us removing the mysql dependency, and refactoring the pieces requiring mysql, and update documentation to reflect that folks will need to specify pulling in mysql (or mariadb, etc) as they want to do? This is somewhat the model we are moving towards with regards to other cookbooks that require other software like tomcat and the dependency on java. The test cookbook shows how to create the wrapper that includes the java install recipe. 

This would be a breaking change so we'd bump the version of this cookbook up, but would allow for folks to not have to pull in code that they don't want to.

**Comment by acoulton** [comment]
Yes, I'm 100% in favour - as you say, it's now an increasingly common pattern with all the official cookbooks that optional dependencies have to be specified separately.

As well as saving us pulling in unwanted code / reducing dependency conflicts, this would also reduce "spooky action at a distance" and avoid resource cloning and similar issues where an end-user is installing both php and mysql on the same instance.

**Comment by gsdevme** [comment]
This hasn't really gone anywhere but I would also favour removing alot of the non-related PHP recipes from this cookbook.

What I really want from this cookbook is a really robust way to install PHP via source/package and manage the .ini and nothing else.

Im currently using this cookbook along with php-fpm cookbook (which manages my pools).

**Comment by gsdevme** [comment]
Would love to see movement on this issue, I see there is a PR. I look forward to it being resolved.

**Comment by iennae** [comment]
Thanks everyone who has posted to this issue, and to @damacus for the PR. I've released version 5.0.0 of this cookbook that has removed this dependency.

**Comment by gsdevme** [comment]
Thanks alot! Very appreciated 🎉🎉🎉
