### ISSUE TITLE
Some default attributes incompatible for Ubuntu 12.04

### ISSUE THREAD

**Issue by Dens49** [chef-cookbooks/php#195]
I just want to inform you about two incompatibilities I found for Ubuntu 12.04 (edit: also Ubuntu 14.04):

### Cookbook version
1.10.1

### Chef-client version
12.18.31

### Platform Details
Ubuntu 12.04
edit: I noticed this also applies to Ubuntu 14.04

### Steps to Reproduce:
include_recipe "php::module_apc"
include_recipe "php::module_sqlite3"

### Expected Result:
installation of these modules

### Actual Result:
The default values for the attributes
`default['php']['apc']['package']    = 'php5-apc'`
`default['php']['sqlite']['package'] = 'php5-sqlite3'`
are wrong for Ubuntu 12.04.

### Fix
Fixed by overwriting them with
`default['php']['apc']['package'] = 'php-apc'`
`default['php']['sqlite']['package'] = 'php5-sqlite'`

**Comment by tas50** [comment]
I'm going to close this out at this point since 12.04 is going EOL in 2 months. We won't be fixing bugs for EOL distros.
