### ISSUE TITLE
PHP 7.0 on Debian Stretch (9.0)

### ISSUE THREAD

**Issue by fancyweb** [chef-cookbooks/php#210]
### Cookbook version
4.2.0

### Chef-client version
13.1.31

### Platform Details
Debian Stretch 9.0

### Scenario:
Install PHP 7.0 (new default PHP in Debian Stretch)

### Steps to Reproduce:
This is how I was using the recipe before upgrading to the new Debian : `include_recipe 'php'`

### Expected Result:
PHP 7.0 gets installed

### Actual Result:
Error message "No candidate version available for php5-cgi, php5, php5-dev, php5-cli"

### TEMP FIX
To make it work I did this in my own recipe : 
```rb
node.default['php']['conf_dir'] = '/etc/php/7.0/cli'
node.default['php']['ext_conf_dir']  = '/etc/php/7.0/conf.d'
node.default['php']['packages'] = %w(php7.0-cgi php7.0 php7.0-dev php7.0-cli php-pear)
```

**Comment by tas50** [comment]
We're in the process of building a bento box for Debian 9 and we just added Debian 9 to Fauxhai. Once these ship we can get this cleaned up and tested

**Comment by tas50** [comment]
https://github.com/chef-cookbooks/php/pull/212 will fix this

**Comment by tas50** [comment]
I'm just about to ship the fix here
