### ISSUE TITLE
Conflict with mysql::client recipe including when Percona used instead of mysql

### ISSUE THREAD

**Issue by pinepain** [chef-cookbooks/php#87]
When Percona used instead of MySQL and php built from source follow apt error occured:

```
==> default: Errors were encountered while processing:
==> default:  percona-server-server-5.6
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: ---- End output of apt-get -q -y install mysql-client-5.5=5.5.38-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-client-5.5=5.5.38-0ubuntu0.14.04.1 returned 100
==> default: [2014-09-19T15:18:16+04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

This line causes the error:
https://github.com/opscode-cookbooks/php/blob/359a6b98c60a06509b726b431b7bed47f18fc594/recipes/source.rb#L25 

Can we somehow specify which recipe mysql::client or percona::client include based on some pre-setting, say some thing like node['php']['mysql_client'] = [mysql, percona](forcing users to manually include desired recipe with client break BC)?

**Comment by gabrielqs** [comment]
+1
